// Cup & Slice frontend interactions + backend integration
let slides=document.querySelectorAll('.slide'),index=0;if(slides.length)setInterval(()=>{slides[index].classList.remove('active');index=(index+1)%slides.length;slides[index].classList.add('active')},4000);
let aboutSlides=document.querySelectorAll('.about-slide'),aboutIndex=0;if(aboutSlides.length)setInterval(()=>{aboutSlides[aboutIndex].classList.remove('active');aboutIndex=(aboutIndex+1)%aboutSlides.length;aboutSlides[aboutIndex].classList.add('active')},3000);
function filterMenu(category,clickedTab){document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));if(clickedTab)clickedTab.classList.add('active');document.querySelectorAll('.menu-grid').forEach(g=>g.style.display=category==='all'||g.dataset.category===category?'grid':'none')}
const API='/api';
async function api(path,data,method){const token=localStorage.getItem('token');const res=await fetch(API+path,{method:method||(data?'POST':'GET'),headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:data?JSON.stringify(data):undefined});const j=await res.json();if(!res.ok)throw Error(j.error||'Something went wrong');return j}
function openSignin(){const m=document.getElementById('signinModal');if(m)m.style.display='block'}function closeSignin(){const m=document.getElementById('signinModal');if(m)m.style.display='none'}
function openDashboard(){location.href='/dashboard.html'}
function logout(){localStorage.clear();location.href='/'}
function updateAuthLink(){const name=localStorage.getItem('username'),role=localStorage.getItem('role'),link=document.getElementById('authLink'),dash=document.getElementById('dashboardLink'),admin=document.getElementById('adminLink');if(name){link.textContent='SIGN OUT ('+name.toUpperCase()+')';link.onclick=logout;if(dash)dash.style.display=role==='customer'?'inline-block':'none'}else{link.textContent='SIGN IN';link.onclick=openSignin;if(dash)dash.style.display='none'}if(admin)admin.style.display='inline-block'}
async function signIn(mode){try{const data={username:document.getElementById('username').value,password:document.getElementById('password').value};if(mode==='register'){data.email=document.getElementById('email').value;data.phone=document.getElementById('phone').value}const r=await api('/auth/'+mode,data);localStorage.setItem('token',r.token);localStorage.setItem('username',r.username);localStorage.setItem('role',r.role);updateAuthLink();document.getElementById('successMsg').textContent=mode==='login'?'Signed in successfully ✅':'Account created successfully ✅';document.getElementById('successMsg').style.display='block';setTimeout(()=>{closeSignin();location=r.role==='admin'?'/admin.html':'/dashboard.html'},600)}catch(e){alert(e.message)}}
let selectedItem={name:'',price:0};
function openOrderPopup(itemName,itemPrice){if(!localStorage.getItem('token')){alert('Please Sign In first to place an order.');openSignin();return}selectedItem={name:itemName,price:itemPrice};document.getElementById('orderPopup').style.display='flex';document.getElementById('popupItemName').textContent=itemName;document.getElementById('popupItemPrice').textContent=itemPrice;document.getElementById('quantity').value=1;document.getElementById('totalPrice').textContent=itemPrice;document.getElementById('customerName').value=localStorage.getItem('username')||'';document.getElementById('orderAddress').value='';document.getElementById('tableNo').value='';document.getElementById('orderTip').value='';document.getElementById('orderNotes').value='';document.getElementById('paymentRef').value='';toggleOrderFields();showPaymentHelp()}
function closeOrderPopup(){document.getElementById('orderPopup').style.display='none'}
function toggleOrderFields(){const type=document.getElementById('orderType').value,addr=document.getElementById('orderAddress'),table=document.getElementById('tableNo');table.style.display=type==='dine-in'?'block':'none';addr.placeholder=type==='delivery'?'Delivery address':'Pickup / order note';document.getElementById('etaPreview').textContent='⏱️ Estimated time: '+(type==='pickup'?20:35)+' minutes'}
function showPaymentHelp(){const p=document.getElementById('paymentMethod').value;document.getElementById('paymentHelp').style.display=['upi','phonepe','paytm'].includes(p)?'block':'none'}
async function confirmOrder(){try{const type=document.getElementById('orderType').value,payment=document.getElementById('paymentMethod').value,payload={item:selectedItem.name,qty:Number(document.getElementById('quantity').value)||1,customerName:document.getElementById('customerName').value,address:document.getElementById('orderAddress').value,tableNo:document.getElementById('tableNo').value,orderType:type,orderSource:document.getElementById('orderSource').value,paymentMethod:payment,paymentRef:document.getElementById('paymentRef').value,tip:Number(document.getElementById('orderTip').value)||0,notes:document.getElementById('orderNotes').value};if(payment==='card_paypal'){const cfg=await api('/config');if(!cfg.razorpay.enabled)throw Error('Online card/UPI gateway is not configured by the restaurant yet. Please choose UPI/PhonePe/Paytm QR or Pay at Cafe.');const r=await api('/payments/razorpay/create',payload);await loadRazorpay();const rz=new Razorpay({key:r.keyId,amount:r.amount,currency:r.currency,name:r.name,description:r.description,order_id:r.razorpayOrderId,prefill:r.prefill,theme:{color:'#111111'},handler:async response=>{try{await api('/payments/razorpay/verify',{orderId:r.internalOrderId,razorpay_payment_id:response.razorpay_payment_id,razorpay_order_id:response.razorpay_order_id,razorpay_signature:response.razorpay_signature});closeOrderPopup();showOrderToast(`Payment verified ✅ Order #${r.internalOrderId} received.`);setTimeout(openDashboard,900)}catch(e){alert(e.message)}}});rz.on('payment.failed',response=>alert('Payment failed: '+(response.error?.description||'Please try again.')));rz.open();return}const r=await api('/orders',payload);closeOrderPopup();showOrderToast(`Order #${r.order.id} received ✅ ETA ${r.etaMinutes} minutes. Admin has been notified.`);setTimeout(openDashboard,900)}catch(e){alert(e.message)}}
function loadRazorpay(){return new Promise((resolve,reject)=>{if(window.Razorpay)return resolve();const s=document.createElement('script');s.src='https://checkout.razorpay.com/v1/checkout.js';s.onload=resolve;s.onerror=()=>reject(Error('Could not load payment gateway'));document.head.appendChild(s)})}
function showOrderToast(msg){const d=document.createElement('div');d.style='position:fixed;right:20px;bottom:20px;z-index:99999;background:#111;color:#fff;padding:16px 20px;border-radius:12px;box-shadow:0 8px 30px #0004';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),6000)}
async function openOrderTracker(){if(!localStorage.getItem('token'))return openSignin();document.getElementById('orderTrackerModal').style.display='flex';try{const [orders,notes]=await Promise.all([api('/orders'),api('/notifications')]);document.getElementById('homeOrderNotifications').innerHTML=notes.slice(0,5).map(n=>`<div style="background:#fff4cc;padding:10px;margin:6px;border-radius:10px"><b>${n.title}</b><br>${n.message}</div>`).join('')||'<p>No notifications</p>';document.getElementById('homeOrders').innerHTML=orders.map(o=>`<div style="padding:12px;margin:8px;background:#fff;border-radius:12px"><b>#${o.id} ${o.item} × ${o.qty}</b><br>Status: <strong>${o.status.replaceAll('_',' ')}</strong> | ETA: ${o.eta_minutes||0} min | ₹${o.total}<br>Payment: ${o.payment_method} / ${o.payment_status}<br><button onclick="location='/dashboard.html'">Open Dashboard</button></div>`).join('')||'<p>No orders yet.</p>'}catch(e){alert(e.message)}}
function closeOrderTracker(){document.getElementById('orderTrackerModal').style.display='none'}
document.addEventListener('DOMContentLoaded',()=>{const tab=document.querySelector('.tab');if(tab)tab.click();updateAuthLink();const q=document.getElementById('quantity');if(q)q.addEventListener('input',()=>document.getElementById('totalPrice').textContent=selectedItem.price*(Number(q.value)||1));});
const reserveForm=document.getElementById('reserveForm');if(reserveForm)reserveForm.addEventListener('submit',async e=>{e.preventDefault();try{const f=e.target;await api('/reservations',{name:f.Name.value,people:f.People.value,at:f.DateTime.value,message:f.Message.value});showOrderToast('Reservation received ✅');f.reset()}catch(err){alert(err.message)}});
function showSocial(msg){alert(msg)}
